export const ADAPTERS = [
  {
    id: 'oneill_kids',
    retailer_name: "O'Neill",
    retailer_domain: 'us.oneill.com',
    brand: "O'Neill",
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://us.oneill.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]', '[data-product-price]'],
    image_selectors: ['img']
  },
  {
    id: 'vans_little_kids_toddlers',
    retailer_name: 'Vans',
    retailer_domain: 'www.vans.com',
    brand: 'Vans',
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://www.vans.com/en-us/c/kids/clothing/little-kids-and-toddlers-3202',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[data-testid*="price"]', '[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'quiksilver_boys',
    retailer_name: 'Quiksilver',
    retailer_domain: 'quiksilver.com',
    brand: 'Quiksilver',
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://quiksilver.com/collections/boys',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'billabong_kids_boys',
    retailer_name: 'Billabong',
    retailer_domain: 'billabong.com',
    brand: 'Billabong',
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://billabong.com/collections/kids-boys',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'hurley_kids',
    retailer_name: 'Hurley',
    retailer_domain: 'hurley.com',
    brand: 'Hurley',
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://hurley.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'volcom_kids',
    retailer_name: 'Volcom',
    retailer_domain: 'volcom.com',
    brand: 'Volcom',
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://volcom.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'red_devil_kids',
    retailer_name: 'Red Devil Clothing',
    retailer_domain: 'reddevilclothing.com',
    brand: 'Red Devil Clothing',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://reddevilclothing.com/collections/all-kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'blackcraft_kids',
    retailer_name: 'Blackcraft',
    retailer_domain: 'blackcraftcult.com',
    brand: 'Blackcraft',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://blackcraftcult.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'brixton_kids',
    retailer_name: 'Brixton',
    retailer_domain: 'brixton.com',
    brand: 'Brixton',
    source_group: 'surf_skate_official',
    source_type: 'official_brand',
    source_listing_url: 'https://brixton.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'kreepsville_kids',
    retailer_name: 'Kreepsville 666',
    retailer_domain: 'store.kreepsville666.com',
    brand: 'Kreepsville 666',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://store.kreepsville666.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'tukshoes_kids',
    retailer_name: 'T.U.K. Shoes',
    retailer_domain: 'tukshoes.com',
    brand: 'T.U.K. Shoes',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://tukshoes.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'blaspheme_boutique_kids',
    retailer_name: 'Blaspheme Boutique',
    retailer_domain: 'blasphemeboutique.com',
    brand: 'Blaspheme Boutique',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://blasphemeboutique.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'hellbunny_kids',
    retailer_name: 'Hell Bunny',
    retailer_domain: 'hellbunny.com',
    brand: 'Hell Bunny',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://hellbunny.com/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'disturbia_kids',
    retailer_name: 'Disturbia',
    retailer_domain: 'disturbia.us',
    brand: 'Disturbia',
    source_group: 'alt_punk_official',
    source_type: 'alt_brand',
    source_listing_url: 'https://disturbia.us/collections/kids',
    listing_card_selector: 'a[href*="/products/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'teepublic_hardcore_punk_kids',
    retailer_name: 'TeePublic',
    retailer_domain: 'www.teepublic.com',
    brand: 'TeePublic',
    source_group: 'marketplace',
    source_type: 'marketplace',
    marketplace_query_context: 'hardcore punk kids t-shirt',
    source_listing_url: 'https://www.teepublic.com/kids-t-shirt/hardcore-punk',
    listing_card_selector: 'a[href*="/kids-t-shirt/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'teepublic_punk_rock_kids',
    retailer_name: 'TeePublic',
    retailer_domain: 'www.teepublic.com',
    brand: 'TeePublic',
    source_group: 'marketplace',
    source_type: 'marketplace',
    marketplace_query_context: 'punk rock kids t-shirt',
    source_listing_url: 'https://www.teepublic.com/kids-t-shirt/punk-rock',
    listing_card_selector: 'a[href*="/kids-t-shirt/"]',
    price_selectors: ['[class*="price"]'],
    image_selectors: ['img']
  },
  {
    id: 'etsy_kids_gothic',
    retailer_name: 'Etsy',
    retailer_domain: 'www.etsy.com',
    brand: 'Etsy',
    source_group: 'marketplace',
    source_type: 'marketplace',
    marketplace_query_context: 'kids gothic clothing',
    source_listing_url: 'https://www.etsy.com/market/kids_gothic_clothing',
    listing_card_selector: 'a[href*="/listing/"]',
    price_selectors: ['[class*="currency"]', '[class*="price"]'],
    image_selectors: ['img']
  }
];
